version: "3"
services:
  # This is a WordPress environment for debugging plugins locally.
  app:
    image: wordpress:6.1.1-apache
    platform: linux/x86_64
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_test
      WORDPRESS_DEBUG: 1
    volumes:
      - ./docker/wp:/var/www/html
      # It's possible to debug guten-bubble copied to folder used from docker.
      # NOTE: Cannot edit them from WordPress running on this container.
      - ./docker/guten-bubble:/var/www/html/wp-content/plugins/guten-bubble:ro
  
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp_test
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    ports:
      - 3306:3306
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql-data:/var/lib/mysql

volumes: 
  mysql-data:
    driver: local